### ISSUE TITLE
Colab Pro with --googleusercontent returns error

### ISSUE THREAD

**Issue by DuckytheQuack** [Bing-su/sd-webui-tunnels#11]
Hello! Thank you for the wonderful extension!
Whenever i use --googleusercontent on Colab pro, it returns this error every time, and doesn't generate a link.

> googleusercontent detected, trying to connect...
> *** Error loading script: googleusercontent.py
>     Traceback (most recent call last):
>       File "/content/drive/MyDrive/colab/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "/content/drive/MyDrive/colab/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "/content/drive/MyDrive/colab/stable-diffusion-webui/extensions/sd-webui-tunnels/scripts/googleusercontent.py", line 20, in <module>
>         tunnel_url = eval_js(js)
>       File "/usr/local/lib/python3.10/dist-packages/google/colab/output/_js.py", line 36, in eval_js
>         kernel = _ipython.get_kernel()
>       File "/usr/local/lib/python3.10/dist-packages/google/colab/_ipython.py", line 24, in get_kernel
>         return get_ipython().kernel
>     AttributeError: 'NoneType' object has no attribute 'kernel'

I am using the latest version of A1111, i am using --no-gradio-queue and the entire startup script is this:

> 'python launch.py --listen --googleusercontent --no-gradio-queue --xformers --enable-insecure-extension-access --theme dark --ckpt-dir "/content/models"'

I would really prefer using googleusercontent over cloudflared or ngrok as it fits my usecase better.
Is there any fix for this issue?

Also as a sidenote, is there a way to get --bore to not "connection errored out" after roughly 30 minutes?
Thank you!

**Comment by webbrain-one** [comment]
Thanks for the clear repro! I opened PR #14, which fixes the `--googleusercontent` failure in Colab Pro by avoiding `eval_js` during script import and running it in the Colab/notebook context instead. This should prevent the `'NoneType' object has no attribute 'kernel'` error and let the link be generated.
